### ISSUE TITLE
send_message函数

### ISSUE THREAD

**Issue by jayfair** [xmiaoq/bossbot#1]
为什么from和to的uid都是0呢，反而name是id，如果在app上沟通，显示的json里的uid不是0呀，小白求解

**Comment by xmiaoq** [comment]
这个结构是我还原的web端结构。from和to的uid都是0呢，反而name是id。

**Comment by jayfair** [comment]
这样确实能够发出消息，但是发出的消息不会被打印出来，而在APP上发出的消息却能回调显示出来(&gt;﹏<)，神奇。



---原始邮件---
发件人: "许渺强"<notifications@github.com&gt;
发送时间: 2020年7月9日(周四) 下午2:51
收件人: "xmiaoq/bossbot"<bossbot@noreply.github.com&gt;;
抄送: "jayfair"<514190739@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [xmiaoq/bossbot] send_message函数 (#1)




 
这个结构是我还原的web端结构。from和to的uid都是0呢，反而name是id。
